site_name: Sotex Staff hub
site_url: https://sotex-lab.github.io/staff-hub/

theme:
  name: material

nav:
  - Home: index.md
  - 'User Guide':
    - 'Workflows docs': workflows/README.md
    - 'Writing your docs': README.md
    - 'Structure Precommit docs': precommit/README.md
    - 'Structure scripts docs': scripts/README.md
    - 'Source code docs': src/README.md
  - Workflows: ''
  - Precommit: ''
  - Scripts: ''
  - Source Code: ''
