site_name: Sotex Staff hub
site_url: https://sotex-lab.github.io/staff-hub/

theme:
  name: material

nav:
  - Home: setup.md
  - Workflows: workflows/
  - Docs template: README.md
  - Precommit: precommit/
  - Scripts: scripts/
  - Source Code: src/
