site_name: Sotex Staff hub
site_url: https://sotex-lab.github.io/staff-hub/
repo_url: https://github.com/sotex-lab/staff-hub
repo_name: staff-hub
site_author: Sotex
# Copyright
copyright: Copyright &copy; 2023 Sotex solutions

theme:
  name: material
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  icon:
    logo: logo

nav:
  - Home: index.md
  - 'User Guide':
    - 'Writing your docs': writing-your-docs.md
    - 'Structure Precommit docs': precommit/precommit.md
    - 'Structure scripts docs': scripts/scripts.md
    - 'Workflows docs': workflows/workflows.md
    - 'Source code docs': src/src.md
    - 'Debugging CI': workflows/debugging-ci.md
  - 'Specification':
    - 'Functionality': src/functionality.md
    - 'Classes':  src/classes.md
