name: Build and lint solution

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v7
      with:
        dotnet-version: '8.0.x'

    - name: Lint the solution
      run: |
        dotnet format StaffHub.sln --verify-no-changes

    - name: Build the solution
      run: |
        dotnet build StaffHub.sln
